# Úkoly

## Indexování a řezání

- Vytvořte NumPy pole s názvem `a` obsahující čísla od 1 do 10.
- Vytvořte 2D NumPy pole s názvem `b` o rozměrech 3x3 a naplňte ho libovolnými čísly.


In [4]:
import numpy as np

In [14]:
a = np.arange(1,11)
print(a)
b = np.random.randint(1,10,(3,3))
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[[7 2 2]
 [8 8 2]
 [8 3 9]]



1. Vyberte z pole `a` třetí a čtvrtý prvek.


In [9]:
print(a[2:4])

[3 4]



2. Vyberte z pole `a` všechny sudá čísla.


In [15]:
b[b%2==0]

array([2, 2, 8, 8, 2, 8])


3. Obraťte vektor `a` (první prvek se stane posledním).


In [16]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])


5. Vyberte z pole `b` druhý řádek.


In [18]:
b[1]

array([8, 8, 2])


6. Vyberte z pole `b` diagonální prvky.


In [19]:
np.diagonal(b)

array([7, 8, 9])


7. Změňte hodnotu prvku na druhém řádku, prvním sloupci v `b` na 100.


In [21]:
b[1,0] = 100
print(b)

[[  7   2   2]
 [100   8   2]
 [  8   3   9]]



8. Vyberte z pole `b` všechny prvky větší než 5.


In [23]:
b[b>5]

array([  7, 100,   8,   8,   9])


9. Vytvořte masku pro pole `b`, která bude True pro všechny prvky menší než 3.


In [24]:
mask = b<3


10. Pomocí masky vyberte z pole `b` všechny prvky menší než 3.




In [25]:
b[mask]

array([2, 2, 2])


## View a copy

- Vytvořte NumPy pole s názvem `a` a naplňte ho libovolnými čísly.


In [33]:
a = np.random.randint(1,9,(5,5))
print(a)

[[6 8 6 1 4]
 [3 5 2 7 7]
 [1 1 6 8 6]
 [5 8 7 8 1]
 [6 5 3 1 6]]



1. Pomocí `a` vytvořte proměnnou `b` obsahující řez druhého řádku a všech sloupců pole `a`.


In [34]:
b = a[1, :]
print(b)

[3 5 2 7 7]



3. Změňte hodnotu prvního prvku v `b`. Jak se tato změna projeví v `a`?


In [36]:
b[0] = 10
print(a)

[[ 6  8  6  1  4]
 [10  5  2  7  7]
 [ 1  1  6  8  6]
 [ 5  8  7  8  1]
 [ 6  5  3  1  6]]



4. Vytvořte proměnnou `c` obsahující **kopii** druhého řádku pole `a`.


In [37]:
c = a[1, :].copy()


5. Změňte hodnotu prvního prvku v `c`. Jak se tato změna projeví v `a`?


In [39]:
c[0] = 100
print(a)

[[ 6  8  6  1  4]
 [10  5  2  7  7]
 [ 1  1  6  8  6]
 [ 5  8  7  8  1]
 [ 6  5  3  1  6]]



6. Zjistěte, zda `b` a `c` sdílí stejná data v paměti.


In [48]:
print(id(b))
print(id(c))

140026314763568
140026314932560


In [49]:
print(a.data)
print(b.data)
print(c.data)


7. Vytvořte proměnnou `d` obsahující diagonální prvky pole `a`.


In [43]:
d = np.diag(a)
print(d)

[6 5 6 8 6]



8. Změňte hodnotu prvního diagonálního prvku v `d`. Jak se tato změna projeví v `a`?



In [50]:
d[0] = 100

ValueError: assignment destination is read-only

9. Vytvořte proměnnou `e` obsahující transpozici pole `a`. Jak je to s pamětí, jedná se o kopii nebo o "array view" ověřte pomocí atributu base.


In [51]:
e = a.T
print(e)
print(a is e.base)

[[ 6 10  1  5  6]
 [ 8  5  1  8  5]
 [ 6  2  6  7  3]
 [ 1  7  8  8  1]
 [ 4  7  6  1  6]]
True




## Lineární algebra

1. Vynásobte matici 5x3 maticí 3x2 (maticový součin).


In [52]:
V = np.random.randint(1,10,(5,3))
U = np.random.randint(1,10,(3,2))

In [54]:
UV = np.dot(V,U)
print(UV)

[[ 35  22]
 [ 60  46]
 [ 88  47]
 [103  73]
 [ 80  56]]


2. Vezměme náhodnou matici 10x2 představující kartézské souřadnice, převeďte je na polární souřadnice.


In [56]:
a = np.random.rand(10,2)
print(a)
a_i = a[:, 0] + a[:, 1]*1j
print(a_i)
r = np.abs(a_i)
phi = np.angle(a_i)
print(f"r = {r}, phi = {phi}")

[[0.34014379 0.65442314]
 [0.63665173 0.15402749]
 [0.11182796 0.6360601 ]
 [0.73384159 0.442497  ]
 [0.61672649 0.39022902]
 [0.36150372 0.08899343]
 [0.55388065 0.90640253]
 [0.5191186  0.95283293]
 [0.59077432 0.58044549]
 [0.81805633 0.1471419 ]]
[0.34014379+0.65442314j 0.63665173+0.15402749j 0.11182796+0.6360601j
 0.73384159+0.442497j   0.61672649+0.39022902j 0.36150372+0.08899343j
 0.55388065+0.90640253j 0.5191186 +0.95283293j 0.59077432+0.58044549j
 0.81805633+0.1471419j ]
r = [0.73754149 0.65501901 0.64581572 0.85692886 0.72981522 0.37229662
 1.06223789 1.085069   0.82820968 0.83118403], phi = [1.09146499 0.23737254 1.39676143 0.54261299 0.56414755 0.24137608
 1.02227264 1.07194188 0.77657953 0.17796477]


3. Vzhledem ke dvěma polím X a Y zkonstruujte Cauchyho matici C (Cij =1/(xi - yj)).


In [58]:
X = np.random.rand(2,10)
Y = np.random.rand(2,10)
C = 1/(X.reshape(-1,1)- Y.reshape(1,-1))
print(C)

[[   1.82606162    2.14901853    1.74022939    2.5190924    16.16849629
     1.67505755   -4.77003731    7.41712104   -3.50249826    2.65747902
     2.257867      2.27432602   17.11610449    6.0942095     2.87965925
    10.81643592  285.52641642   -2.7504109     2.05112989    4.11678983]
 [ -26.68809826   -8.34948735  -95.60553768   -5.31552526   -1.91114016
    84.04856085   -1.25827552   -2.22087326   -1.14862386   -4.78927083
    -7.03231673   -6.87730328   -1.89871487   -2.37526114   -4.20462704
    -2.02986073   -1.71941183   -1.05409781  -10.25006395   -2.92236316]
 [  21.1457947   -28.56553638   13.45877492   -9.67421597   -2.28056803
    10.345702     -1.40849458   -2.73588291   -1.27251329   -8.06195194
   -17.40945993  -16.48934617   -2.26289699   -2.97401548   -6.53284738
    -2.4516773    -2.01274626   -1.15751732  -78.12650095   -3.8845782 ]
 [   1.39873778    1.58069694    1.34781693    1.77219494    4.36390974
     1.30839009  -23.61926151    3.30986813   -8.45974651    

4. Uvažujme náhodný vektor o tvaru (100,2) představující souřadnice, najděte vzdálenosti bod po bodu.


In [62]:
x = np.random.rand(100,2)
np.sqrt(np.sum((x.reshape(-1,1,2) - x.reshape(1,-1,2))**2, axis=2))

array([[0.        , 0.67903544, 0.47079084, ..., 0.50873619, 0.24481669,
        0.68664125],
       [0.67903544, 0.        , 0.24572832, ..., 1.00863278, 0.54470023,
        0.4541852 ],
       [0.47079084, 0.24572832, 0.        , ..., 0.76295756, 0.30198771,
        0.33172517],
       ...,
       [0.50873619, 1.00863278, 0.76295756, ..., 0.        , 0.47450901,
        0.75434311],
       [0.24481669, 0.54470023, 0.30198771, ..., 0.47450901, 0.        ,
        0.44620439],
       [0.68664125, 0.4541852 , 0.33172517, ..., 0.75434311, 0.44620439,
        0.        ]])

5. Ověřte empiricky na náhodné matici, že platí $(AB)^T = B^T A^T$


In [67]:
A = np.random.rand(5,5)
B = np.random.rand(5,5)
print(A)
print(B)
AB = np.dot(A,B)
AB_t = np.dot(B.T, A.T)
print(AB.T == AB_t)
np.isclose(AB.T, AB_t, rtol=1e-6)

[[0.78415793 0.87591934 0.53026503 0.36491431 0.8822868 ]
 [0.48057482 0.33997489 0.85680315 0.59655703 0.55698992]
 [0.78926897 0.98074226 0.1244235  0.89889655 0.10097135]
 [0.33849206 0.80679243 0.51185238 0.28988735 0.39901762]
 [0.19311798 0.88415523 0.59617392 0.63145226 0.84744659]]
[[0.92974418 0.25613024 0.37208314 0.57418546 0.91797773]
 [0.56440058 0.19961949 0.56118118 0.04892699 0.77036313]
 [0.01898162 0.07779364 0.47389497 0.56649904 0.54548125]
 [0.09349556 0.70913419 0.77467921 0.18689853 0.42116594]
 [0.25534623 0.82628586 0.66726333 0.49906001 0.73779097]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

6. Pro náhodné 1D vektory $u, v$ vypočítejte dyadický součin $uv$ $$(uv)_{ij} = u_iv_j$$ pomocí `newaxis`. Zkontrolujte s `np.outer(u, v)`


In [76]:
u = np.random.randint(1,5,5)
v = np.random.randint(1,5,5)
print(u, v)
np.outer(u,v)
u * v.reshape(-1,1)


[3 2 3 2 2] [4 3 2 1 1]


array([[12,  8, 12,  8,  8],
       [ 9,  6,  9,  6,  6],
       [ 6,  4,  6,  4,  4],
       [ 3,  2,  3,  2,  2],
       [ 3,  2,  3,  2,  2]])

7. Vypočítejte hodnost matice o velikosti 5x6 naplněnou hodnotami 0, 1, 2, 3 ... . Byly by jste schopni zdůvodnit proč je hodnost taková jaká je?


In [77]:
A = np.arange(0,30).reshape(5,6)
print(A)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


92.37342858597923


## Funkce nad poli
1. Vytvořte pole 10x10 s náhodnými hodnotami a najděte minimální a maximální hodnoty.


In [101]:
F = np.random.randint(1,250,(10,10))
print(F)

[[ 29 172 115 163  24 242 102 165  83 164]
 [ 55 214  68 248 239 219 209  30 137 135]
 [103 102 152 237 140 236  74  55 230 156]
 [133 215  45 171 208  45 202 172  58  67]
 [ 32 215 185 235  84 160  29  28 167 197]
 [216 182  21 216 139 223 240  91  25 165]
 [ 33 171 248 165  33   7  40  25   5 189]
 [181  26  50  74   1 185 141  71 142 243]
 [ 56 230 183 103 124  70 159 108 134  27]
 [196  68 211 225 150  83   6 227  98 221]]


In [102]:
print(F.min())
print(F.max())

1
248


2. Vytvořte náhodný vektor o velikosti 30 a najděte střední hodnotu.



In [103]:
f = np.random.randint(1, 250, 30)
print(f.mean())

148.3


3. Uvažujme celočíselný vektor Z, které z těchto výrazů jsou platné?
   ```python
   Z**Z
   2 << Z >> 2
   Z <- Z
   1j*Z
   Z/1/1
   Z<Z>Z
   ```



In [107]:
Z = np.random.randint(1, 10, (10,1))

Z

array([[1],
       [7],
       [9],
       [5],
       [1],
       [9],
       [7],
       [7],
       [8],
       [8]])

In [112]:
1j*Z

array([[0.+1.j],
       [0.+7.j],
       [0.+9.j],
       [0.+5.j],
       [0.+1.j],
       [0.+9.j],
       [0.+7.j],
       [0.+7.j],
       [0.+8.j],
       [0.+8.j]])

4. Jaký je výsledek následujícího výrazu? 
   ```python
   0 * np.nan
   np.nan == np.nan
   np.inf > np.nan
   np.nan - np.nan
   np.nan in set([np.nan])
   0.3 == 3 * 0.1
   ```


In [113]:
np.nan == np.nan

False

In [114]:
np.inf > np.nan

False

5. Jaké jsou výsledky následujících výrazů?
   ```python
   np.array(0) / np.array(0)
   np.array(0) // np.array(0)
   np.array([np.nan]).astype(int).astype(float)
   ```



6. Jak najít společné (stejné) hodnoty mezi dvěma poli? 



7. Jak vypočítat ((A+B)*(-A/2)) přímo v poli (bez kopírování)?




8. Vytvořte náhodný vektor o velikosti 10 a seřaďte ho.



9. Vezměme daný vektor, jak přidat 1 ke každému prvku indexovanému druhým vektorem (dejte pozor na opakované indexy)? 

